<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-3L9G43G" failures="1" tests="1" name="testRunner.TestRunnerClass" time="3.189" errors="0" timestamp="2024-12-04T16:21:16 IST" skipped="0">
  <testcase classname="testRunner.TestRunnerClass" name="runScenario" time="3.189">
    <failure message="verify Msg expected [Your OTP has expired, Please try again] but found [Your account has been blocked for 15 minutes. Please try after 15 minutes ]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: verify Msg expected [Your OTP has expired, Please try again] but found [Your account has been blocked for 15 minutes. Please try after 15 minutes ]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at stepDefinition.Tc2_External_Login_Otp.the_response_status_for_invalid_otp_should_be_with_message_error_description_and_error_code(Tc2_External_Login_Otp.java:667)
at âœ½.the response status for Invalid otp should be 200 with message "Your account has been blocked for 15 minutes. Please try after 15 minutes ", errorDescription "Unable to process Your Request" and errorCode 1003(file:///C:/Users/Welcome/eclipse-workspace/Harley_Project/src/test/resources/Features/External_Login_Otp.feature:241)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- testRunner.TestRunnerClass -->
